/*
* Create table in bookStore database 
* Author: namduong
* Github: @namduongit
*/

DROP DATABASE IF EXISTS bookStore;
CREATE DATABASE IF NOT EXISTS bookStore;
USE bookStore;


CREATE TABLE tacGia (
    maTacGia INT AUTO_INCREMENT PRIMARY KEY,
    tenTacGia VARCHAR(100) NOT NULL,
    trangThai ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') DEFAULT 'ACTIVE',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE nhaXuatBan (
    maNXB INT AUTO_INCREMENT PRIMARY KEY,
    tenNXB VARCHAR(100) NOT NULL,
    trangThai ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') DEFAULT 'ACTIVE',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE theLoai (
    maTheLoai INT AUTO_INCREMENT PRIMARY KEY,
    tenTheLoai VARCHAR(100) NOT NULL,
    trangThai ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') DEFAULT 'ACTIVE',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE loaiBia (
    maLoaiBia INT AUTO_INCREMENT PRIMARY KEY,
    tenLoaiBia VARCHAR(100) NOT NULL,
    trangThai ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') DEFAULT 'ACTIVE',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sach (
    maSach INT AUTO_INCREMENT PRIMARY KEY,
    tenSach VARCHAR(100) NOT NULL,
    soTrang INT,
    kichThuoc INT,
    moTa VARCHAR(1000),
    maTacGia INT,
    maTheLoai INT,
    maLoaiBia INT,
    maNXB INT,
    namXuatBan DATE,
    giaTran INT,
    giaBan INT,
    hinhAnh VARCHAR(200),
    trangThai ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') DEFAULT 'ACTIVE',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Khóa ngoại
    FOREIGN KEY (maTacGia) REFERENCES tacGia(maTacGia) ON DELETE SET NULL,
    FOREIGN KEY (maTheLoai) REFERENCES theLoai(maTheLoai) ON DELETE SET NULL,
    FOREIGN KEY (maLoaiBia) REFERENCES loaiBia(maLoaiBia) ON DELETE SET NULL,
    FOREIGN KEY (maNXB) REFERENCES nhaXuatBan(maNXB) ON DELETE SET NULL
);


CREATE TABLE phieuGiamGia (
    maPGG INT AUTO_INCREMENT PRIMARY KEY,
    tenPGG VARCHAR(100) NOT NULL,
    type ENUM('PERCENTAGE', 'FIXED_AMOUNT') NOT NULL,
    phanTram INT CHECK (phanTram BETWEEN 0 AND 100),
    toiThieu INT,
    toiDa INT,
    ngayBatDau DATE NOT NULL,
    ngayKetThuc DATE NOT NULL,
    trangThai ENUM('ACTIVE', 'EXPIRED', 'DISABLED') DEFAULT 'ACTIVE',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE nhaCungCap (
    maNCC INT AUTO_INCREMENT PRIMARY KEY,
    tenNCC VARCHAR(100) NOT NULL,
    soDT VARCHAR(20) UNIQUE,
    email VARCHAR(100) UNIQUE,
    diaChi VARCHAR(100),
    trangThai ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') DEFAULT 'ACTIVE',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE quyen (
    maQuyen INT AUTO_INCREMENT PRIMARY KEY,
    tenQuyen VARCHAR(100) NOT NULL UNIQUE,
    trangThai ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE chucNang (
    maChucNang INT AUTO_INCREMENT PRIMARY KEY,
    tenChucNang VARCHAR(100) NOT NULL UNIQUE,
    trangThai ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE'
);

CREATE TABLE chiTietQuyen (
    maQuyen INT,
    maChucNang INT,
    PRIMARY KEY (maQuyen, maChucNang),
    FOREIGN KEY (maQuyen) REFERENCES quyen(maQuyen) ON DELETE CASCADE,
    FOREIGN KEY (maChucNang) REFERENCES chucNang(maChucNang) ON DELETE CASCADE
);


CREATE TABLE nguoiDung (
    maNguoiDung INT AUTO_INCREMENT PRIMARY KEY,
    hoVaTen VARCHAR(100) NOT NULL,
    soDT VARCHAR(20) UNIQUE,
    email VARCHAR(100) UNIQUE,
    tenTaiKhoan VARCHAR(100) NOT NULL UNIQUE,
    matKhau VARCHAR(255) NOT NULL,
    maQuyen INT,
    trangThai ENUM('ACTIVE', 'LOCKED', 'DISABLED') DEFAULT 'ACTIVE',
    hinhAnh VARCHAR(100),
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (maQuyen) REFERENCES quyen(maQuyen) ON DELETE SET NULL
);

CREATE TABLE diaChiNguoiDung (
    maDiaChi INT AUTO_INCREMENT PRIMARY KEY,
    maNguoiDung INT NOT NULL,
    diaChi VARCHAR(255) NOT NULL,
    macDinh BOOLEAN DEFAULT FALSE,

    FOREIGN KEY (maNguoiDung) REFERENCES nguoiDung(maNguoiDung) ON DELETE CASCADE
);


CREATE TABLE phuongThucThanhToan (
    maPTTT INT AUTO_INCREMENT PRIMARY KEY,
    tenPhuongThuc ENUM('CODE', 'CARD') NOT NULL
);


CREATE TABLE thanhToanNguoiDung (
    maNguoiDung INT NOT NULL,
    maPTTT INT NOT NULL,
    maThe VARCHAR(16),
    ngayHetHan DATE,
    maBaoMat CHAR(3),

    PRIMARY KEY (maNguoiDung, maPTTT),
    FOREIGN KEY (maNguoiDung) REFERENCES nguoiDung(maNguoiDung) ON DELETE CASCADE,
    FOREIGN KEY (maPTTT) REFERENCES phuongThucThanhToan(maPTTT) ON DELETE CASCADE
);



CREATE TABLE donHang (
    maDonHang INT AUTO_INCREMENT PRIMARY KEY,
    ngayTaoDon DATETIME DEFAULT CURRENT_TIMESTAMP,
    maKhachHang INT NOT NULL,
    maKhuyenMai INT DEFAULT NULL,
    diaChiGiao VARCHAR(100) NOT NULL,
    tongTienThu INT NOT NULL DEFAULT 0,
    trangThai ENUM('CHO_XAC_NHAN', 'DANG_GIAO', 'DA_GIAO', 'DA_HUY') DEFAULT 'CHO_XAC_NHAN',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (maKhachHang) REFERENCES nguoiDung(maNguoiDung) ON DELETE CASCADE,
    FOREIGN KEY (maKhuyenMai) REFERENCES phieuGiamGia(maPGG) ON DELETE SET NULL
);


CREATE TABLE chiTietDonHang (
    maDonHang INT,
    maSach INT,
    soLuong INT NOT NULL CHECK (soLuong > 0),
    tienThu INT NOT NULL CHECK (tienThu >= 0),
    
    PRIMARY KEY (maDonHang, maSach),
    FOREIGN KEY (maDonHang) REFERENCES donHang(maDonHang) ON DELETE CASCADE,
    FOREIGN KEY (maSach) REFERENCES sach(maSach) ON DELETE CASCADE
);


CREATE TABLE phieuNhap (
    maPhieuNhap INT AUTO_INCREMENT PRIMARY KEY,
    ngayTaoPhieu DATETIME DEFAULT CURRENT_TIMESTAMP,
    taiKhoanNhanVien VARCHAR(100) NOT NULL,
    maNCC INT NOT NULL,
    tongTienNhap INT NOT NULL DEFAULT 0,
    trangThai ENUM('CHO_XAC_NHAN', 'DA_NHAP', 'DA_HUY') DEFAULT 'CHO_XAC_NHAN',
    ngayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (taiKhoanNhanVien) REFERENCES nguoiDung(tenTaiKhoan) ON DELETE CASCADE,
    FOREIGN KEY (maNCC) REFERENCES nhaCungCap(maNCC) ON DELETE CASCADE
);

CREATE TABLE chiTietPhieuNhap (
    maPhieuNhap INT,
    maSach INT,
    giaNhap INT NOT NULL CHECK (giaNhap > 0),
    soLuong INT NOT NULL CHECK (soLuong > 0),
    tienNhap INT NOT NULL CHECK (tienNhap >= 0),
    
    PRIMARY KEY (maPhieuNhap, maSach),
    FOREIGN KEY (maPhieuNhap) REFERENCES phieuNhap(maPhieuNhap) ON DELETE CASCADE,
    FOREIGN KEY (maSach) REFERENCES sach(maSach) ON DELETE CASCADE
);


